FROM dhi.io/maven:3-jdk25-debian13-dev AS build

WORKDIR /app

COPY pom.xml ./pom.xml
COPY src ./src/

RUN --mount=type=cache,target=/Users/makcymal/.m2 \
    mvn clean package -DskipTests


FROM whisper:py3.14-deb13

WORKDIR /app

COPY --from=build /opt/java/openjdk/25 /opt/java/openjdk-25/
COPY --from=build /app/target/*.jar ./app.jar

ENV JAVA_HOME=/opt/java/openjdk-25
ENV PATH="$JAVA_HOME/bin:$PATH"

CMD ["java", "-jar", "app.jar"]
