app:
  version: '@project.version@'

server:
  port: ${SERVER_PORT}

spring:
  main:
    banner-mode: off
  application:
    name: polylang
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show-sql: ${JPA_SHOW_SQL}
        format-sql: true
        hbm2ddl:
          auto: validate
  liquibase:
    enabled: true
    liquibase-schema: public
    database-change-log-table: changelog
    database-change-log-lock-table: changelog_lock
    change-log: classpath:/db/changelog.yaml

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED}

security:
  public-key: ${PUBLIC_KEY}
  private-key: ${REFRESH_KEY}
  access-token-validity: ${ACCESS_TOKEN_VALIDITY}
  refresh-token-validity: ${REFRESH_TOKEN_VALIDITY}
  email-confirmation-code-validity: ${EMAIL_CONFIRMATION_CODE_VALIDITY}
  cookies-attr-secure: ${COOKIES_ATTR_SECURE}
  cookies-attr-same-site: ${COOKIES_ATTR_SAME_SITE}

talks:
  speech-records-dir: ${SPEECH_RECORDS_DIR}
  speech-transcriptions-dir: ${SPEECH_TRANSCRIPTIONS_DIR}
  transcribe-by-snippets-of-duration: ${TRANSCRIBE_BY_SNIPPETS_OF_DURATION}
  whisper-path: ${WHISPER_PATH}
  whisper-model: ${WHISPER_MODEL}
  whisper-models-dir: ${WHISPER_MODELS_DIR}
  whisper-thread-pool-size: ${WHISPER_THREAD_POOL_SIZE}
  waiting-whisper-response-timeout: ${WAITING_WHISPER_RESPONSE_TIMEOUT}
  detect-silence-by-no-speech-prob-threshold: ${DETECT_SILENCE_BY_NO_SPEECH_PROB_THRESHOLD}
  silence-timeout-to-stop-recording: ${SILENCE_TIMEOUT_TO_STOP_RECORDING}
