server:
  port: 3232

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/polylang
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

jwt:
  public-key: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFBZ1FDbm5vZDBhUm1jaVJPMzh4T1oxZUJtTlY4RTR0VkY0SzRKclJuMXVEb2JhZUYzMUNYTExUTWRWenRoTUg0VEZpcTI1Q2VrekdjQlpkNHNwcG1qUFRQNXJqeUFsNjR1ZFZPY3IvVWRNSXl4aUlFelZtNmh0SmlDMENYUzFlaGtyMjYyYjdJdmZJbDZWaC9nVnJwM2w2RzBoOUdKU1o4bUx0c3VER2s2MGE4RTdRPT0gbWFrY3ltYWxAYmFja2JvbmUubG9jYWwK
  private-key: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFsd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFJRUFwNTZIZEdrWm5Ja1R0L01UbWRYZ1pqVmZCT0xWUmVDdUNhMFo5Ymc2RzJuaGQ5UWx5eTB6CkhWYzdZVEIrRXhZcXR1UW5wTXhuQVdYZUxLYVpvejB6K2E0OGdKZXVMblZUbksvMUhUQ01zWWlCTTFadW9iU1lndEFsMHQKWG9aSzl1dG0reUwzeUplbFlmNEZhNmQ1ZWh0SWZSaVVtZkppN2JMZ3hwT3RHdkJPMEFBQUlRN0VIU0tPeEIwaWdBQUFBSApjM05vTFhKellRQUFBSUVBcDU2SGRHa1puSWtUdC9NVG1kWGdaalZmQk9MVlJlQ3VDYTBaOWJnNkcybmhkOVFseXkwekhWCmM3WVRCK0V4WXF0dVFucE14bkFXWGVMS2Fab3oweithNDhnSmV1TG5WVG5LLzFIVENNc1lpQk0xWnVvYlNZZ3RBbDB0WG8KWks5dXRtK3lMM3lKZWxZZjRGYTZkNWVodElmUmlVbWZKaTdiTGd4cE90R3ZCTzBBQUFBREFRQUJBQUFBZ0FXNVZpclZnLwpoaWZmZmtKeUV6dW93QytwR3lKVkpUajkzb3VXQTR3Rk03VkdYQkt1RTdVK21HbHhLRWsybVhjakg0ckpubUdRWmxNaWNZCk1WcnZ0aHljZGFLWlBTKzhFU0hCNXVsekErNVJDMktmTmhaNjZadU54UmVsUGhuMmRyQlc3dlRVR0M0cFd1NXpIM2FGaE8KT3NWM2VGbStPVG94TFk1QjlvS3dxQkFBQUFRRHBtalJvVzhzR1VPR2pVcGYyM3ZDOGp2aGZkdDVSdG5oS1Z6R0tzWEZlKwo4QjVxNWZVQWhISHdZeklxRi95QzNVNHNqWFd0b3d1R0pFWm5TUEpTVStnQUFBQkJBTjVjTEFudnNuNSt2by9wQVdUM25oCm92K2lYYjBGOWFNRUVscEphV1dNVmcraXFQQnBDc3ZuNTZsYVU3T0NobWhBQitweXo3WmJiMDNLTzYvQVFsZzEwQUFBQkIKQU1ENlNpaW1XZlpHWEVxRjVEWUlyeDJYOUFmL3dBOTA4bEN6Sm00L20wckFVVDhLZXJQczhwS292dWU2RlhUS0NibUdKUQpVa3BVeGJuK0lNc2hLVGZ0RUFBQUFYYldGclkzbHRZV3hBWW1GamEySnZibVV1Ykc5allXd0JBZ01FCi0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=
  access-token-validity: PT10M
  refresh-token-validity: PT24H

speaking:
  speech-records-dir: /app/speech-records
  speech-transcriptions-dir: /app/speech-transcriptions
  transcribe-by-snippets-of-duration: PT15S
  whisper-path: /app/whisper-venv/bin/whisper
  whisper-model: SMALL_EN
  whisper-models-dir: /app/whisper-models
  whisper-thread-pool-size: 4
  waiting-whisper-response-timeout: PT1M
  detect-silence-by-no-speech-prob-threshold: '0.8'
  silence-timeout-to-stop-recording: PT10S
