app:
  version: '@project.version@'

server:
  port: ${SERVER_PORT}

spring:
  main:
    banner-mode: off
  application:
    name: polylang
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show-sql: ${JPA_SHOW_SQL}
        format-sql: true
        hbm2ddl:
          auto: validate
  liquibase:
    enabled: true
    liquibase-schema: public
    database-change-log-table: changelog
    database-change-log-lock-table: changelog_lock
    change-log: classpath:/db/changelog.yaml

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED}

jwt:
  public-key: ${PUBLIC_KEY}
  private-key: ${REFRESH_KEY}
  access-token-validity-seconds: ${ACCESS_TOKEN_VALIDITY_SECONDS}
  refresh-token-validity-days: ${REFRESH_TOKEN_VALIDITY_DAYS}
